# 端口号
server:
    port: 8888

# 数据库配置
spring:
    datasource:
        username: root
        password: 965123
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/hooya_shop?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong

# mybatis
mybatis:
    type-aliases-package: top.hooya.shop.pojo
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# pagehelper
pagehelper:
    helper-dialect: mysql
    page-size-zero: true
    reasonable: true
    support-methods-arguments: true
