# 端口号
server:
    port: 8888
    tomcat:
        uri-encoding: utf-8

# 数据库配置
spring:
    datasource:
        name: druidDataSource
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://127.0.0.1:3306/hooya_shop?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong
            username: root
            password: 965123

# mybatis
mybatis:
    type-aliases-package: top.hooya.shop.pojo
#    configuration:
#        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# pagehelper
pagehelper:
    helper-dialect: mysql
    page-size-zero: true
    reasonable: true
    support-methods-arguments: true
